### ISSUE TITLE
Comment qu'on fait pour rajouter des bidules si on n'a pas les droits

### ISSUE THREAD

**Issue by Dubs120** [d-j-a-y/irenAtelier#1]
Voila, j'ai essayé de téléverser un fichier, et bien je suis disablé mec!

**Comment by Dubs120** [comment]
@d-j-a-y comme cela, c'est mieux?
![Youpala](https://user-images.githubusercontent.com/73911790/104429396-d9eaff00-5585-11eb-8db8-f527964d10d0.jpg)

**Comment by d-j-a-y** [comment]
Je pourrais recup l'image ici mais ce n'est pas le bon chemin.

Du coup, tente de le faire par un pull request depuis ton depot.
1- Ajout d'une image dans ton depot
2- Pull request vers origin/master  (d-j-a-y/master)

**Comment by Dubs120** [comment]
@d-j-a-y   Hé, reste poli, hein!

**Comment by Dubs120** [comment]
@d-j-a-y tu as tu vu que j'ai créé un fork? Et bien je l'ai mise dedans. Bon, c'est juste pour tester les fonctionnalités, car ce crobard n'a rien à faire dans l'atelier mobile
